In [4]:
import numpy as np

In [ ]:
### define the probe geometry and the sites, then apply the mapping from sites to channels using the appropriate headstage


In [33]:
# for th a4x16-poly3-5mm-20s-200-16-h64

# a single shank sites and positions
poly_3_shank_sites = np.array([5, 1, 2, 3, 4, 6, 11, 7, 10, 8, 9, 12, 16, 15, 14, 13])
poly_3_shank_geom = [[0, i*20 + 10] for i in range(5)] + [[20, i*20] for i in range(6)] + [[40, i*20] for i in range(5)]
poly_3_shank_arr = np.array(poly_2_shank_geom)

# the probe site postions
a4x16_poly3 = dict()
a4x16_poly3['geom'] = np.vstack([poly_3_shank_arr + np.array([200 * i, 0]) for i in range(4)])
a4x16_poly3['channel_groups'] = {i: dict({'sites': poly_3_shank_sites + i*16}) for i in np.arange(4)}

a4x16_poly3['channel_groups']

{0: {'sites': array([ 5,  1,  2,  3,  4,  6, 11,  7, 10,  8,  9, 12, 16, 15, 14, 13])},
 1: {'sites': array([21, 17, 18, 19, 20, 22, 27, 23, 26, 24, 25, 28, 32, 31, 30, 29])},
 2: {'sites': array([37, 33, 34, 35, 36, 38, 43, 39, 42, 40, 41, 44, 48, 47, 46, 45])},
 3: {'sites': array([53, 49, 50, 51, 52, 54, 59, 55, 58, 56, 57, 60, 64, 63, 62, 61])}}

In [88]:
# site to channel
nnx64_intan = {'sites' : np.array([34, 43, 44, 45, 33, 46, 47, 48, 17, 18, 19, 32, 20, 21, 22, 31,
                          42, 41, 40, 35, 39, 38, 37, 36, 29, 28, 27, 26, 30, 25, 24, 23,
                          64, 62, 60, 58, 56, 54, 52, 50, 15, 13, 11, 9, 7, 5, 3, 1, 
                          63, 61, 59, 57, 55, 53, 51, 49, 16, 14, 12, 10, 8, 6, 4, 2]),
               'channels' : np.array(list(range(16, 47, 2)) +  \
                            list(range(17, 48, 2)) + \
                            list(range(15, 0, -2)) + list(range(63, 47, -2)) +\
                            list(range(14, -1, -2)) + list(range(62, 46, -2)))
                                    
              }

nnx64_intan

{'sites': array([34, 43, 44, 45, 33, 46, 47, 48, 17, 18, 19, 32, 20, 21, 22, 31, 42,
        41, 40, 35, 39, 38, 37, 36, 29, 28, 27, 26, 30, 25, 24, 23, 64, 62,
        60, 58, 56, 54, 52, 50, 15, 13, 11,  9,  7,  5,  3,  1, 63, 61, 59,
        57, 55, 53, 51, 49, 16, 14, 12, 10,  8,  6,  4,  2]),
 'channels': array([16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 17,
        19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 15, 13,
        11,  9,  7,  5,  3,  1, 63, 61, 59, 57, 55, 53, 51, 49, 14, 12, 10,
         8,  6,  4,  2,  0, 62, 60, 58, 56, 54, 52, 50, 48])}

In [104]:
def get_probe_channels(prb_dict: dict, hs_dict: dict) -> dict:
    chgrp = prb_dict['channel_groups']
    site_chan_arr = np.vstack([hs_dict['sites'], hs_dict['channels']])
    print(site_chan_arr.shape)
    # sort by sites
    site_chan_arr = site_chan_arr[:, np.argsort(site_chan_arr[0])]
    for k, v in chgrp.items():
        sites = v['sites']
        v['channels'] = np.array([hs_dict['channels'][hs_dict['sites'] == s] for s in sites]).flatten()
    
    return prb_dict
        
prb_dict = get_probe_channels(a4x16_poly3, nnx64_intan)

(2, 64)


In [105]:
prb_dict

{'geom': array([[  0,  10],
        [  0,  30],
        [  0,  50],
        [  0,  70],
        [  0,  90],
        [ 20,   0],
        [ 20,  20],
        [ 20,  40],
        [ 20,  60],
        [ 20,  80],
        [ 20, 100],
        [ 40,   0],
        [ 40,  20],
        [ 40,  40],
        [ 40,  60],
        [ 40,  80],
        [200,  10],
        [200,  30],
        [200,  50],
        [200,  70],
        [200,  90],
        [220,   0],
        [220,  20],
        [220,  40],
        [220,  60],
        [220,  80],
        [220, 100],
        [240,   0],
        [240,  20],
        [240,  40],
        [240,  60],
        [240,  80],
        [400,  10],
        [400,  30],
        [400,  50],
        [400,  70],
        [400,  90],
        [420,   0],
        [420,  20],
        [420,  40],
        [420,  60],
        [420,  80],
        [420, 100],
        [440,   0],
        [440,  20],
        [440,  40],
        [440,  60],
        [440,  80],
        [600,  10],
        [600

In [98]:
np.searchsorted(site_chan_arr[0], [5, 7])

array([4, 6])

In [83]:
(nnx64_intan['sites']).size

64

In [90]:
np.where(nnx64_intan['sites']==32)

(array([11]),)

In [74]:
orig_idx

array([47, 63, 46, 62, 45, 61, 44, 60, 43, 59, 42, 58, 41, 57, 40, 56,  8,
        9, 10, 12, 13, 14, 31, 30, 29, 27, 26, 25, 24, 28, 15, 11,  4,  0,
       19, 23, 22, 21, 20, 18, 17, 16,  1,  2,  3,  5,  6,  7, 55, 39, 54,
       38, 53, 37, 52, 36, 51, 35, 50, 34, 49, 33, 48, 32])

In [93]:
orig_idx = nnx64_intan['sites'].argsort()
np.searchsorted(nnx64_intan['sites'][orig_idx], np.array([31, 4, 22]))

array([30,  3, 21])

In [72]:
nnx64_intan['sites']

array([34, 43, 44, 45, 33, 46, 47, 48, 17, 18, 19, 32, 20, 21, 22, 31, 42,
       41, 40, 35, 39, 38, 37, 36, 29, 28, 27, 26, 30, 25, 24, 23, 64, 62,
       60, 58, 56, 54, 52, 50, 15, 13, 11,  9,  7,  5,  3,  1, 63, 61, 59,
       57, 55, 53, 51, 49, 16, 14, 12, 10,  8,  6,  4,  2])

In [40]:
list(range(16, 46)) + \
list(range(17, 48))

[16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47]

In [8]:
        "channel_groups": {
            1: {"channels": np.arange(0, 8)},
            2: {"channels": np.arange(8, 16)},
            3: {"channels": np.arange(16, 24)},
            4: {"channels": np.arange(24, 32)},

In [3]:
probe_maps = {
    "Buzsaki32": {
        "geom": [
            [i, j]
            for i, j in zip(
                [
                    0,
                    -13,
                    13,
                    -20,
                    20,
                    -27,
                    27,
                    -34,
                    200,
                    187,
                    213,
                    180,
                    220,
                    173,
                    227,
                    166,
                    400,
                    387,
                    413,
                    380,
                    420,
                    373,
                    427,
                    366,
                    600,
                    587,
                    613,
                    580,
                    620,
                    573,
                    627,
                    566,
                ],
                [
                    0,
                    20,
                    40,
                    60,
                    80,
                    100,
                    120,
                    140,
                    0,
                    20,
                    40,
                    60,
                    80,
                    100,
                    120,
                    140,
                    0,
                    20,
                    40,
                    60,
                    80,
                    100,
                    120,
                    140,
                    0,
                    20,
                    40,
                    60,
                    80,
                    100,
                    120,
                    140,
                ],
            )
        ],
        "channel_groups": {
            1: {"channels": np.arange(0, 8)},
            2: {"channels": np.arange(8, 16)},
            3: {"channels": np.arange(16, 24)},
            4: {"channels": np.arange(24, 32)},
        },
    },
}

NameError: name 'np' is not defined